spring.application.name=ifmap-backend

spring.datasource.url=jdbc:mysql://localhost:3306/ifmap_db
spring.datasource.username=root
spring.datasource.password=VishnuRaj2411

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8080